#!/usr/bin/env ruby

# Putting this rake tasks here because they don't get along if put as a
# dependency of the same task.

system 'rake gems:unpack'
system 'rake gems:build'
system 'rake rails:freeze:gems'
